default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: furima_dev
  username: <%= ENV['DATABASE_DEV_USERNAME'] %>
  password: <%= ENV['DATABASE_DEV_PASSWORD'] %>
  host: localhost

test:
  <<: *default
  database: furima_test
  username: <%= ENV['DATABASE_TEST_USERNAME'] %>
  password: <%= ENV['DATABASE_TEST_PASSWORD'] %>
  host: localhost

production:
  <<: *default
  database: furima_production
  url: <%= ENV['DATABASE_URL'] %>
