default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: furima_35860_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  <<: *default
  database: furima_35860_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  <<: *default
  database: heroku_a78dfda05d6b281
  username: b313c839c2b73f
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  reconnect: true
