default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: furima_35860_development

test:
  <<: *default
  database: furima_35860_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
