development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: furima_35860_development

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: furima_35860_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>