default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>

development:
  <<: *default
  database: furima_35860_development

test:
  <<: *default
  database: furima_35860_test

production:
  <<: *default
  database: furima_35860_production
  username: b313c839c2b73f
  password: a2405219
  host: us-cdbr-east-04.cleardb.com
  reconnect: true
